//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCours
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> fk_Person_Id { get; set; }
        public Nullable<System.Guid> fk_Course_Id { get; set; }
        public Nullable<System.DateTime> Date_Registered { get; set; }
        public Nullable<System.DateTime> Date_Completed { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
